logging:
  level:
    ROOT: info
    org.hibernate.SQL: DEBUG
    en.g3.groovy: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: groovy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/hark
    username: xander
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spotify_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify_clone
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8081

okta:
  oauth2:
    issuer: https://dev-zkxshn2vfjlbojfq.us.auth0.com/
    client-id: mgmFgG4wwHWuHSBjFMlw0tVv9SLPp3bk
    client-secret: nXjojNVL0g_x5-BfCC-1uyAViuto_VDp849JUM268VEZAnkNIV4WubiGaNO2wy3g
